{{- if .Values.traefikIngressRoute.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "spring-boot-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spring-boot-app.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- range .Values.traefikIngressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  {{- if or .Values.traefikIngressRoute.tls.enabled .Values.traefikIngressRoute.tls.store .Values.traefikIngressRoute.tls.secretName }}
  tls:
    {{- if .Values.traefikIngressRoute.tls.store }}
    store: {{ .Values.traefikIngressRoute.tls.store }}
    {{- end }}
    {{- if .Values.traefikIngressRoute.tls.secretName }}
    secretName: {{ .Values.traefikIngressRoute.tls.secretName }}
    {{- if .Values.traefikIngressRoute.tls.domains }}
    domains:
      {{- range .Values.traefikIngressRoute.tls.domains }}
      - main: {{ .main | quote }}
        {{- if .sans }}
        sans:
          {{- range .sans }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
  routes:
    {{- range .Values.traefikIngressRoute.routes }}
    - match: {{ if $.Values.traefikIngressRoute.quickMatch }}{{ $.Values.traefikIngressRoute.quickMatch }}{{ else }}{{ .match }}{{ end }}
      kind: {{ .kind }}
      {{- $hasMiddlewares := or .middlewares $.Values.traefikIngressRoute.stripPrefix.enabled }}
      {{- if $hasMiddlewares }}
      middlewares:
        {{- if $.Values.traefikIngressRoute.stripPrefix.enabled }}
        - name: {{ $.Values.traefikIngressRoute.stripPrefix.middlewareName | default (printf "%s-strip-prefix" (include "spring-boot-app.fullname" $)) }}
          namespace: {{ $.Release.Namespace }}
        {{- end }}
        {{- range .middlewares }}
        - name: {{ .name }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
        {{- end }}
      {{- end }}
      services:
        {{- range .services }}
        - name: {{ .name | default (include "spring-boot-app.fullname" $) }}
          port: {{ .port | default $.Values.service.port }}
        {{- end }}
    {{- end }}
{{- end }}
