apiVersion: v2
name: spring-boot-app
description: A Helm chart for Spring Boot applications
type: application
version: 0.0.12
appVersion: "0.0.12"
keywords:
  - spring-boot
  - java
maintainers:
  - name: Mr Krystof
    email: erkrystof@users.noreply.github.com