replicaCount: 1

image:
  repository: docker-private.privpub.krystof.io/krystof-io/spring-boot-hello
  tag: "1.0.0-SNAPSHOT-9744156"
  pullPolicy: Always

imagePullSecrets:
  - name: docker-private-ro
  
springBoot:
  profiles:
    active: "dev"

opentelemetry:
  enabled: true
  serviceName: "spring-boot-hello"
  endpoint: "http://open-telemetry-collector-daemonset-opentelemetry-collector.monitoring.svc.cluster.local:4317"
  config:
    resourceAttributes: "deployment.environment=dev,deployment.namespace=kio-dev"
    javaagentAddThreadDetails: "true"
        
traefikIngressRoute:
  enabled: true
  quickMatch: Host(`kio-dev.private.krystof.io`) && PathPrefix(`/spring-boot-hello`)
  stripPrefix:
      enabled: true
      prefixes: 
        - "/spring-boot-hello"